# Generated by Django 4.1.6 on 2023-02-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['created'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AddField(
            model_name='table',
            name='username',
            field=models.CharField(default='user', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
