# Generated by Django 4.1.6 on 2023-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_table_options_table_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['created'], 'verbose_name': 'Column', 'verbose_name_plural': 'Columns'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='column',
            name='heading_color',
            field=models.CharField(choices=[('WH', 'White'), ('YE', 'Yellow'), ('RE', 'Red'), ('GR', 'Green'), ('BL', 'Blue'), ('PU', 'Purple'), ('PI', 'Pink')], default='WH', max_length=2),
        ),
        migrations.AddField(
            model_name='column',
            name='table_url',
            field=models.URLField(default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='column',
            name='username',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='column_url',
            field=models.URLField(default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
