# Generated by Django 4.1.6 on 2023-02-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_table_options_table_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['created'], 'verbose_name': 'Column', 'verbose_name_plural': 'Columns'},
        ),
        migrations.AddField(
            model_name='column',
            name='heading_color',
            field=models.CharField(choices=[('WH', 'White'), ('YE', 'Yellow'), ('RE', 'Red'), ('GR', 'Green'), ('BL', 'Blue'), ('PU', 'Purple'), ('PI', 'Pink')], default='WH', max_length=2),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='main.table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='column',
            name='username',
            field=models.CharField(default='abc', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
