# Generated by Django 4.1.6 on 2023-02-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_column_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.table'),
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.column'),
        ),
    ]
