# Generated by Django 4.1.6 on 2023-02-19 17:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_column_table_task_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=[], size=None),
            preserve_default=False,
        ),
    ]
