# Generated by Django 4.1.6 on 2023-02-19 17:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_table_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=500), size=None),
        ),
    ]
