# Generated by Django 4.1.6 on 2023-02-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_column_tasks_alter_table_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='table',
            name='columns',
        ),
    ]
