# Generated by Django 4.1.6 on 2023-02-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_column_tasks_remove_table_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='slug',
            field=models.CharField(default='abc', max_length=1000),
            preserve_default=False,
        ),
    ]
