# Generated by Django 4.1.6 on 2023-03-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_column_table_url_remove_task_column_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='heading_color',
        ),
    ]
